routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/news');
});
Route::resource('/news', 'StoriesController')->only('index', 'show');
Route::get('/author/{id}', 'AuthorController@show')->name('show.author');
Route::post('view/{id}', 'StoriesController@viewStory')->name('view.story');

app/Comments.php
<?php

namespace App;

use App\Service\AgeService;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Comments
 * @property int $id
 * @property string $text
 * @property string $author
 * @property int $parent_id
 * @property int $time
 * @property-read  string $comment_age
 *
 * @package App
 */
class Comments extends Model
{
    protected $table = 'comments';
    protected $primaryKey = 'id';
    public $incrementing = false;
    public $timestamps = false;
    protected $fillable = ['id','text','author','parent_id','time'];
    protected $appends = ['comment_age'];

    public function story()
    {
        return $this->belongTo('App\Stories', 'id', 'parent_id');
    }

    public function replies()
    {
        return $this->hasMany(Comments::class, 'parent_id');
    }

    public function getCommentAgeAttribute()
    {
        return (new AgeService($this->time))->getAge();
    }
}

app/Stories.php
<?php

namespace App;

use App\Service\AgeService;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Stories
 *
 * @property int $id
 * @property string $title
 * @property string $author
 * @property string $text
 * @property string $story_url
 * @property int $type
 * @property int $score
 * @property int $time
 * @property int $comment_count
 * @property bool $viewed
 * @property-read string $age
 * @property-read string $host
 */

class Stories extends Model
{
    const TOP_STORIES = 1;
    const NEW_STORIES = 2;
    const BEST_STORIES = 3;
    const NOT_VIEWED = 0;
    const VIEWED = 1;

    protected $table = 'stories';
    protected $primaryKey = 'id';
    public $incrementing = false;
    public $timestamps = false;
    protected $fillable = ['id','title','author','story_url','type', 'score','time', 'comment_count', 'text', 'viewed'];
    protected $appends = ['age', 'host'];

    public function comments()
    {
        return $this->hasMany('App\Comments', 'parent_id', 'id')->orderByDesc('time');
    }

    public function getAgeAttribute(): string
    {
        return (new AgeService($this->time))->getAge();
    }

    public function getHostAttribute()
    {
        if ($this->story_url != ''){
            return parse_url($this->story_url)['host'];
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Service\ImportNewsRequestService;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    /**
     * @var ImportNewsRequestService
     */
    private $requestService;

    public function __construct(ImportNewsRequestService $requestService)
    {
        $this->requestService = $requestService;
    }

    public function show($author)
    {
        $user = $this->requestService->getAuthor($author);

        return view('author.show', compact('user'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StoriesController.php
<?php

namespace App\Http\Controllers;

use App\Events\StoryViewedEvent;
use App\Stories;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Event;

class StoriesController extends Controller
{
    public function index()
    {
        $query = Stories::orderByDesc('time');
        if (request()->filled('type')){
            switch (request()->get('type')) {
                case "newstories":
                    $query->where('type', Stories::NEW_STORIES);
                    break;
                case "topstories":
                    $query->where('type', Stories::TOP_STORIES);
                    break;
                case "beststories":
                    $query->where('type', Stories::BEST_STORIES);
                    break;
                default:
                    $query->whereIn('type', Stories::BEST_STORIES, Stories::BEST_STORIES, Stories::NEW_STORIES);
            }
        }

       $stories = $query->simplePaginate(30);

       return view('stories.index', compact('stories'));
    }

    public function show($id)
    {
       $story = Stories::findOrfail($id);

       return view('stories.show', compact('story'));
    }

    public function viewStory($id)
    {
        $story = Stories::findOrfail($id);
        event(new StoryViewedEvent($story));
    }
}

resources/views/author/_show_author.blade.php
<table class="table-borderless">
    <tbody>
    <tr>
        <td valign="top">user:</td>
        <td ><a href="" class="hnuser">{{$user['id']}}</a></td>
    </tr>
    <tr>
        <td valign="top">created:</td>
        <td><a href="">{{$user['created']}}</a></td>
    </tr>
    <tr>
        <td valign="top">karma:</td>
        <td>{{$user['karma']}}</td>
    </tr>
    <tr>
        <td valign="top">about:</td>
        <td>{{$user['about']}}</td>
    </tr>
    <tr>
        <td></td>
        <td><a href=""><u>submissions</u></a></td>
    </tr>
    <tr>
        <td></td>
        <td><a href=""><u>comments</u></a></td>
    </tr>
    <tr>
        <td></td>
        <td><a href=""><u>favorites</u></a></td>
    </tr>
    </tbody>
</table>

resources/views/author/show.blade.php
@extends('layouts.app')
@section('title', 'Stories')
@push('head')
    <style>
        a { color: #000000; }
    </style>
@endpush
@section('content')
    <div class="card my-3">
        <div class="card-body table-responsive p-0">
            @include('stories.partials._hacker_news_table',['user', $user])
        </div>
    </div>
@endsection

resources/views/comments/_show_comment.blade.php
@foreach($comments as $comment)
    <div class="ml-3">
        <div>
            <span>
                <i class="fas fa-caret-up"></i>
                <a href="" class="text-muted">{{$comment->author}}</a>
                <span>
                    <a href="" class="text-muted">{{$comment->comment_age}} [-]</a>
                </span>
            </span>
        </div>
        <div>
            <span>{!! $comment->text !!}</span>
            <p><a href="">reply</a></p>
        </div>
    </div>
    <div class="ml-5">
    @include('comments._show_comment',['comments' => $comment->replies])
    </div>
@endforeach

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Hacker News - @yield('title')</title>

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}"></script>

    <!-- Styles -->
    <link type="text/css" rel="stylesheet" href="{{ mix('css/app.css') }}">

    @stack('head')
</head>
<body>
<div id="app">
    @yield('body')
    <main class="">
        @yield('content')
    </main>
</div>

@stack('scripts')
</body>
</html>

resources/views/stories/index.blade.php
@extends('layouts.app')
@section('title', 'Stories')
@push('head')
    <style>
        a { color: #000000; }
    </style>
@endpush
@section('content')

    <div class="card my-3">
        <div class="card-body table-responsive p-0">
            @include('stories.partials._hacker_news_table', ['stories' => $stories])
            {{ $stories->links() }}
        </div>
    </div>

@endsection
@push('scripts')
    <script>
        var routes = {
                viewStory : "{!! route('view.story', -1) !!}",
            }
    </script>
    <script src="{{mix('/js/story/view-story.js')}}"></script>
@endpush

resources/views/stories/partials/_hacker_news_table.blade.php
<table class="table table-hover table-sm" style="background-color: #f6f6ef">
    <tbody>
    <tr>
        <td style="background-color: #ff6600">
            <table class="table-borderless">
                <tbody>
                <tr>
                    <td><a href="/"><img src="https://news.ycombinator.com/y18.gif" style="border:1px solid #ffffff;"></a></td>
                    <td>
                        <span>
                            <span>
                                <a href="/" class="font-weight-bold">Hacker News</a>
                            </span>
                             {!! link_to_route('news.index', 'new', ['type' => 'newstories'], ['target' => '_blank']) !!}
                            |
                            {!! link_to_route('news.index', 'best', ['type' => 'beststories'], ['target' => '_blank']) !!}
                            |
                            {!! link_to_route('news.index', 'top', ['type' => 'topstories'], ['target' => '_blank']) !!}
                            |
                            <a href="">comments</a>
                        </span>
                    </td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    <tr class="h-10"></tr>
    <tr>
        <td>
            @isset($stories)
                @include('stories.partials._story_header', ['stories' => $stories])
            @endisset
            @isset($user)
                @include('author._show_author', ['user' => $user])
            @endisset
            @isset($comments)
                <div class="col-5">
                    {!! Form::textarea('reply',null,['class'=>'form-control', 'rows' => 2, 'cols' => 40]) !!}
                    {!! Form::button('add comment', ['class' => 'my-3']) !!}
                </div>
                <? /** @var \App\Comments $comment */  ?>
                @include('comments._show_comment', ['comments' => $comments])
            @endisset
        </td>
    </tr>
    </tbody>
</table>

resources/views/stories/partials/_story_header.blade.php
<table class="table-borderless">
    <tbody>
    <?php /** @var \App\Stories $story */ ?>
    @foreach($stories as $story)
        <tr>
            <td>
                @if(count($stories) > 1)
                    <span>{{ ($stories ->currentpage()-1) * $stories ->perpage() + $loop->iteration}}</span>
                @endif
            </td>
            <td><a href=""><i class="fas fa-1x fa-caret-up"></i></a></td>
            <td>
                <a href="{{$story->story_url}}" id="{{$story->id}}"
                   class="story-link {{$story->viewed == \App\Stories::VIEWED ? 'text-muted' : ''}}">{{$story->title}}</a>
                <?php $host = isset($story->host) ? '('.link_to($story->story_url, $story->host, ['class' => 'text-muted']).')' : '' ?>
                <span> {!! $host  !!}</span>
                @if(count($stories) == 1)
                    <p class="my-2">{!! $story->text !!}</p>
                @endif
            </td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td class="small">
                <span>{{$story->score}} {{$story->score == 1 ? 'point' : 'points'}}</span>
                by
                <a href="{{route('show.author',$story->author)}}">{{$story->author}}</a>
                <span> <a href="{{route('news.show', $story->id)}}">{{$story->age}}</a></span>
                <span></span>
                |
                <a href="">hide</a>
                |
                {{link_to("https://hn.algolia.com/?query={$story->title}", 'past')}}
                |
                {{link_to("http://www.google.com/search?q={$story->title}", 'web')}}
                |
                <a href="{{route('news.show', $story->id)}}">discuss</a>
                @if($story->comment_count > 0)
                    |
                    <a href="{{route('news.show', $story->id)}}">{{$story->comment_count}}{{$story->comment_count == 1 ? ' comment' : ' comments'}} </a>
                @endif
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/stories/show.blade.php
@extends('layouts.app')
@section('title', 'Stories')
@push('head')
    <style>
        a { color: #000000; }
    </style>
@endpush
@section('content')
    <div class="container-fluid">
        <div class="card my-3">
            <div class="card-body table-responsive p-0">
                @include('stories.partials._hacker_news_table', ['stories' => [$story], 'comments' => $story->comments])
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        var routes = {
            viewStory : "{!! route('view.story', -1) !!}",
        }
    </script>
    <script src="{{mix('/js/story/view-story.js')}}"></script>
@endpush